---
title: "Analysis"
author: "Molly Leavens"
date: "10/31/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(formattable)
both_waves <- read_csv("farmerData_bothWaves.csv")
```

## Average yield

```{r pressure, echo=FALSE}
both_waves %>% 
  summarise()

boxplot(both_waves$gghhsize)

#need to remove outliers on this
boxplot(both_waves$ggsavings)

#need to remove outliers on this
boxplot(both_waves$ggfsizeacres)

#need to remove outliers on this
boxplot(both_waves$ggfsizecocoaacres)

#remove 1 outlier
boxplot(both_waves$ggbuyers)

#need to remove outliers on this
boxplot(both_waves$ggharvestcocoaKG)

#interesting data point!
#need to look into exactly how this is calculated
boxplot(both_waves$ggfraclost)
hist(both_waves$ggfraclost)

#SUPER INTERESTING
boxplot(both_waves$ggschoolinghhhead)

#count genders
#gggenderhhhead.1 gives same result
#1 is male, 0 is female
sum(both_waves$gggenderhhhead, na.rm = TRUE) 
#answer is 4332, which is 81% of the survey

#huge outliers in here. someone cannot be 200 years old...
boxplot(both_waves$ggmeanage)

#huge outlier
boxplot(both_waves$ggyieldall_cocarea)

#this would be interesting viewed as a density plot (it gets harder close to 1)
boxplot(both_waves$ggfractionsold)

#outliers
boxplot(both_waves$ggincomecocoa)

#number of household heads who ever schooled
#1 is yes, 0 is no #STILL NEED TO CONFIRM THIS WITH BECCA
sum(both_waves$ggeverschoolhhhead, na.rm = TRUE) 
#answer is 4013, which is 75% of the survey

#########why is this not working?####
both_waves$ggyieldall_cocarea <- as.numeric(both_waves$ggyieldall_cocarea)
both_waves %>% 
median(ggyieldall_cocarea, ra.rm = TRUE)

#histogram of price


#does 1 mean yes or no?
boxplot(both_waves$gghhhwives)
          
```

```{r}
###this creates three new summary dataframes
###I output these tables in kable in shiny app
###NOTE TO SELF: need to group by wave (2008 or 2014)
###Each table formatted into percentage

#percentage with access to physical resources 
#COULD ADDITIONALLY GROUP BY GENDER AND REGION 
phys_resources <- 
  both_waves %>% 
    select(ggcar, ggchainsaw, ggmistblower, ggelectric, surveyWave) %>% 
    summarise(per_car = 
                      percent(sum(both_waves$ggcar, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggcar))), digits = 0),
              per_chainsaw = 
                      percent(sum(both_waves$ggchainsaw, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggchainsaw))), digits = 0),
              per_mistblower = 
                      percent(sum(both_waves$ggmistblower, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggmistblower))), digits = 0),
              per_electric = 
                      percent(sum(both_waves$ggelectric, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggelectric))), digits = 0)
  )

#percentage with access to educational/training resources
#COULD ADDITIONALLY GROUP BY GENDER AND REGION
ed_resources <- 
  both_waves %>% 
    select(ggtraining, ggliterate, ggeverschoolhhhead, surveyWave) %>% 
    summarise(per_training = 
                      percent(sum(both_waves$ggtraining, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggtraining))), digits = 0),
              per_literate = 
                      percent(sum(both_waves$ggliterate, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggliterate))), digits = 0),
              per_everschoolhhhead = 
                      percent(sum(both_waves$ggeverschoolhhhead, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggeverschoolhhhead))), digits = 0)
  )

#percentage with access to financial/organizational resources
#COULD ADDITIONALLY GROUP BY GENDER AND REGION
fin_resources <- 
  both_waves %>% 
    select(ggreceivedloan, ggorggroup, ggbank) %>% 
    summarise(per_receivedloan = 
                      percent(sum(both_waves$ggreceivedloan, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggreceivedloan))), digits = 0),
              per_orggroup = 
                      percent(sum(both_waves$ggorggroup, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggorggroup))), digits = 0),
              per_bank = 
                      percent(sum(both_waves$ggbank, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggbank))), digits = 0)
)

#migrant status/ ggborninvillage
#something about health (healthcare and malaria)

#percentage with access to chemical inputs 
#COULD ADDITIONALLY GROUP BY GENDER AND REGION
chem_resources <-
  both_waves %>% 
    select(ggdumfert, gginsect, ggherb, ggfungi) %>% 
    summarise(per_dumfert = 
                      percent(sum(both_waves$ggdumfert, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggdumfert))), digits = 0),
              per_insect = 
                      percent(sum(both_waves$gginsect, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$gginsect))), digits = 0),
              per_fungi = 
                      percent(sum(both_waves$ggfungi, na.rm = TRUE)
                      /(5371-sum(is.na(both_waves$ggfungi))), digits = 0)
)

#create output tables 
phys_resources %>% 
  kable(caption = "Total number of unique candidate IDs and comittee IDs for each party",
      col.names = c("Party","Candidate IDs", "Committee IDs"))

fin_resources %>% 
  kable(caption = "Total number of unique candidate IDs and comittee IDs for each party",
      col.names = c("Party","Candidate IDs", "Committee IDs"))
  
chem_resources %>% 
  kable(caption = "Total number of unique candidate IDs and comittee IDs for each party",
      col.names = c("Party","Candidate IDs", "Committee IDs"))

```

```{r}
#setequal to find if .1 variables are different.
setequal(both_waves$gginvestment, both_waves$gginvestment.1)
setequal(both_waves$ggtraining, both_waves$ggtraining.1)
setequal(both_waves$ggorggroup, both_waves$ggorggroup.1)

#they are all identicle. NOTE TO SELF: need to remove in an ealier cleaning

```

```{r}
#child labor 

#internal

#external

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}

lm()

```

